apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysqlUsername: {{ .Values.secrets.mysqlUsername | b64enc | quote }}
  mysqlPassword: {{ .Values.secrets.mysqlPassword | b64enc | quote }}