eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME_LIBRARY:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/certifDB?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:louey}
    password: ${DB_PASSWORD:louey}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /library/v3/api-docs
  swagger-ui:
    path: /library/swagger-ui.html

server:
  port: 8020

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always