apiVersion: apps/v1
kind: Deployment
metadata:
  name: certifications-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: certifications
  template:
    metadata:
      labels:
        app: certifications
    spec:
      containers:
      - name: certifications
        image: loueydenden/certifications-service:latest
        ports:
        - containerPort: 8070
        envFrom:
        - configMapRef:
            name: app-configmap
        env: 
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysqlUsername

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysqlPassword