apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: loueydenden/order-service:latest
        ports:
        - containerPort: 8060
        envFrom:
        - configMapRef:
            name: app-configmap
        env: 
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysqlUsername

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysqlPassword